sudo: required
language: node_js
node_js:
  - '8'
  - '10'

cache:
  directories:
    - $HOME/.yarn-cache

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint
  - yarn test ng-context --watch=false --code-coverage --browsers ChromeHeadless

addons:
  chrome: stable
